modLoader="javafml" #mandatory
#UPDATE
loaderVersion="[40,)"
license="All rights reserved"

[[mods]] #mandatory

modId="simpleshops"
version="1.1.4"
displayName="Simple Shops"

#updateJSONURL="http://myurl.me/"
#issueTrackerURL="http://my.issue.tracker/"

displayURL="https://wolforcept.github.io"
logoFile="logo.png"

credits="Wolforce"
authors="Wolforce"

# The description text for the mod (multi line!) (#mandatory)
description='''
A simple shop mod
'''